DROP TABLE "USER" IF EXISTS;

CREATE TABLE REVINFO (
    REV      INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    REVTSTMP BIGINT
);

CREATE TABLE MACHINE (
    ID                  BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    SHARE_PASSWORD_ENC VARCHAR(255),
    SHARE_USERNAME     VARCHAR(255),
    DESTINATION_FOLDER  VARCHAR(2000)                     NOT NULL,
    ENABLED             BOOLEAN                           NOT NULL,
    IPV4                VARCHAR(255),
    NAME                VARCHAR(255) UNIQUE               NOT NULL,
    SALT                VARCHAR(255),
    SECURE_KEY_ENC      VARCHAR(255),
    SOURCE_FOLDER       VARCHAR(2000)                     NOT NULL
);

CREATE TABLE "PUBLIC"."MACHINE_SCHEDULES" (
    MACHINE_ID BIGINT NOT NULL,
    SCHEDULES  VARCHAR(255)
);
ALTER TABLE "PUBLIC"."MACHINE_SCHEDULES"
    ADD CONSTRAINT FK_KEQRT87TYR6C15OG25EHAQJ5D FOREIGN KEY (MACHINE_ID) REFERENCES "PUBLIC"."MACHINE" (ID);

CREATE TABLE MACHINE_AUD (
    ID                  BIGINT  NOT NULL,
    REV                 INTEGER NOT NULL,
    REVTYPE             TINYINT,
    SHARE_PASSWORD_ENC VARCHAR(255),
    SHARE_USERNAME     VARCHAR(255),
    DESTINATION_FOLDER  VARCHAR(2000),
    ENABLED             BOOLEAN,
    IPV4                VARCHAR(255),
    NAME                VARCHAR(255),
    SALT                VARCHAR(255),
    SECURE_KEY_ENC      VARCHAR(255),
    SOURCE_FOLDER       VARCHAR(2000),
    CONSTRAINT CONSTRAINT_73 PRIMARY KEY (ID, REV)
);

CREATE TABLE MACHINE_SCHEDULES_AUD (
    REV        INTEGER      NOT NULL,
    MACHINE_ID BIGINT       NOT NULL,
    SCHEDULES  VARCHAR(255) NOT NULL,
    REVTYPE    TINYINT,
    CONSTRAINT CONSTRAINT_9 PRIMARY KEY (REV, MACHINE_ID, SCHEDULES)
);

ALTER TABLE MACHINE_AUD
    ADD FOREIGN KEY (REV) REFERENCES REVINFO (REV);

ALTER TABLE MACHINE_SCHEDULES_AUD
    ADD FOREIGN KEY (REV) REFERENCES REVINFO (REV);

CREATE TABLE "PUBLIC"."ACTIVITY_LOG" (
    ID           IDENTITY PRIMARY KEY NOT NULL,
    DATA         VARCHAR(255)         NOT NULL,
    LEVEL        VARCHAR(255),
    OBJECT_CLASS VARCHAR(255)         NOT NULL,
    OBJECT_ID    BIGINT               NOT NULL,
    TAGS         VARCHAR(255),
    TIMESTAMP    TIMESTAMP            NOT NULL
);

CREATE TABLE "PUBLIC"."BACKUP" (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESTINATION_FOLDER VARCHAR(255) NOT NULL,
    FINISHED_AT TIMESTAMP,
    SOURCE_FOLDER VARCHAR(255) NOT NULL,
    STARTED_AT TIMESTAMP NOT NULL,
    STATE VARCHAR(255) NOT NULL,
    MACHINE_ID BIGINT NOT NULL,
    CONSTRAINT FK_C7KXI2XO3G42KVS5G2WV041DC FOREIGN KEY (MACHINE_ID) REFERENCES MACHINE (ID)
);

